
package zBACKUP_ISBN13_SOAP;

//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 454B24E0A38865EA03E6ACA83D152297C2F148C1571E29803969C2BBA15327BC36BB0E7F53838994B37C5276F4B3AA95D6F0708C5E863D366DFAD3194C864598
//------------------------------------------------------------------------
public interface IQGDateTimeParser
{
    String getStringFromDateTime(java.time.ZonedDateTime date);
    String getStringFromDate(java.time.LocalDate date);
    String getStringFromTime(java.time.LocalTime date);
    String getStringFromDuration(java.time.Duration date);
    java.time.ZonedDateTime parse(String value);
    java.time.LocalDate parseLocal(String value);
    java.time.Duration parseDuration(String value);
    java.time.LocalTime parseTime(String value);
}
