

package zBACKUP_ISBN13_SOAP;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 454B24E0A38865EA03E6ACA83D152297C2F148C1571E29803969C2BBA15327BC36BB0E7F53838994B37C5276F4B3AA95D6F0708C5E863D366DFAD3194C864598
//------------------------------------------------------------------------

public class IQGSoapException extends java.lang.Exception
{
    private org.w3c.dom.Element _details=null;
    private Object _fault = null;
    
    public IQGSoapException(String message,org.w3c.dom.Element details)
    {
        super(message);
        _details=details;
    }

    public IQGSoapException(Object fault)
    {
        _fault=fault;
    }

    public Object getFault() {
        return _fault;
    }


    public org.w3c.dom.Element getDetails() {
        return _details;
    }
}