
package ISBN_SOAP;
//------------------------------------------------------------------------
//
// Generated by www.easywsdl.com
// Version: 9.0.0.0
//
// Created by Quasar Development 
//
// This class has been generated for test purposes only and cannot be used in any commercial project.
// To use it in commercial project, you need to generate this class again with Premium account.
// Check https://EasyWsdl.com/Payment/PremiumAccountDetails to see all benefits of Premium account.
//
// Licence: 0E82BB53D374CBB02A5D6DB247B4AD180F99172EE4DDF1D07982F040C4BD3E2400CD3EB79369F9377A0240F7D661830EE033E13F7CFAF67A52887A4000CBADBE
//------------------------------------------------------------------------
import java.util.HashMap;


public class FKMResponseData
{
    private HashMap< String,String> headers = new HashMap< String,String>();
    private String body;

    public HashMap< String,String> getHeaders()
    {
        return headers;
    }
    
    public String getBody()
    {
        return body;
    }

    public void setBody(String body)
    {
        this.body=body;
    }
}